spring.application.name=debug.camel.yaml


# Tell Camel where your YAML routes are
camel.springboot.routes-include-pattern=classpath:camel/*.yaml

# Enable debugger (only in dev!)
camel.debug.enabled=true
camel.debug.breakpoints=*